apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpu-fpga-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: tpu-fpga-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: tpu-fpga-device-plugin-ds
    spec:
      hostNetwork: true
      tolerations:
        - key: eicas.com/tpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      containers:
        - image: 192.168.2.20:30002/eicas/tpu-fpga-device-plugin:v1.0.0
          name: tpu-device-plugin-ctr
          ports:
            - containerPort: 2112
              name: metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: opt
              mountPath: /opt/sophon
            - name: sys
              mountPath: /sys/class/bm-sophon
            - name: proc
              mountPath: /root/proc/bmsophon
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: opt
          hostPath:
            path: /opt/sophon
        - name: sys
          hostPath:
            path: /sys/class/bm-sophon
        - name: proc
          hostPath:
            path: /proc/bmsophon