apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eicas-tpu-device-plugin
  namespace: kube-system
  labels:
    k8s-app: eicas-tpu-device-plugin
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  selector:
    matchLabels:
      k8s-app: eicas-tpu-device-plugin
  template:
    metadata:
      labels:
        k8s-app: eicas-tpu-device-plugin
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: eicas
        hostPath:
            path: /home/kubernetes/bin/eicas
            type: Directory
      - name: pod-resources
        hostPath:
            path: /var/lib/kubelet/pod-resources
      containers:
      - image: "gcr.io/gke-release/eicas-tpu-device-plugin@sha256:622d701b1ccebbb25c01e4326a3a6c2aa001b2507f66c89a3d65b9778e6b02ee"
        command: ["/usr/bin/eicas-tpu-device-plugin", "-logtostderr", "--enable-health-monitoring"]
        name: eicas-tpu-device-plugin
        ports:
        - name: "metrics"
          containerPort: 2112
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/eicas/lib64
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 20Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
        - name: eicas
          mountPath: /usr/local/eicas
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources
  updateStrategy:
    type: RollingUpdate
